---
title: "Background"
---
</br>

**PhD 2019 - Understanding *in vivo* modelling of Depression**

<a href="http://camarades.info/" target="_blank">CAMARADES</a>, University of Edinburgh & <a href="http://tnu.au.dk/" target="_blank">TNU</a>, Aarhus University. Supervisors: Prof Malcolm Macleod & Prof Gregers Wegener. 


*Selected Publications:*

<a href="https://doi.org/10.1186/s13643-019-0942-7" target="_blank">Bannach-Brown, A., Przybyła, P., Thomas, J., Rice, A.S., Ananiadou, S., Liao, J. and Macleod, M.R., 2019. Machine learning algorithms for systematic review: reducing workload in a preclinical review of animal studies and reducing human screening error. Systematic reviews, 8(1), p.23.</a>

<a href="https://doi.org/10.1136/bmjos-2018-000017" target="_blank">Bannach-Brown, A., Tillmann, S., MacLeod, M.R. and Wegener, G., 2019. Administration of galacto-oligosaccharide prebiotics in the Flinders Sensitive Line animal model of depression. BMJ Open Science, 3(1), p.e000017.</a>

<a href="http://www.clinsci.org/content/131/20/2525" target="_blank">Bahor, Z., Liao, J., Macleod, M.R., Bannach-Brown, A., McCann, S.K., Wever, K.E., Thomas, J., Ottavi, T., Howells, D.W., Rice, A. and Ananiadou, S., 2017. Risk of bias reporting in the recent animal focal cerebral ischaemia literature. Clinical Science, 131(20), pp.2525-2532.</a>


<a href="https://onlinelibrary.wiley.com/doi/full/10.1002/ebm2.24" target="_blank">Bannach‐Brown, A., Liao, J., Wegener, G., & Macleod, M. (2016). Understanding in vivo modelling of depression in non‐human animals: a systematic review protocol. Evidence-based Preclinical Medicine, 3(2), 20-27. </a>

*Invited Talks:* 

Bannach-Brown, A., (August, 2017). Machine Learning Approaches to Assist Screening in Preclinical Systematic Reviews. Platform presentation at: 4th International Symposium on Systematic Review and Meta-Analysis of Laboratory Animal Studies, NIEHS, NC, USA
 
</br>

**MSc in Integrative Neuroscience 2015 - Motor Symptoms in Dementia as Measured by the EMAS & Relationships to MRI Biomarkers**

University of Edinburgh. Supervisor: Dr Thomas Bak. 

</br>

**BSc in Psychology 2014 - <a href="http://e-space.mmu.ac.uk/576663/" target="_blank">Visio-Motor Integration in Developmental Dyslexia</a>.**

Edinburgh Napier University. Supervisor: Dr Alex Willis. 