---
title: "Datasets & Code"
output: html_document
---
## 2019
Currently working on Integrated Interface Project
See <a href="https://github.com/icasr/I3" terget="_blank" GitHub</a> for ongoing progress. 

## 2018
“Machine learning algorithms in systematic reviews: reducing workload in preclinical biomedical sciences and reducing human screening error.” - Data and R code available.

<Link to publication on <a href="https://doi.org/10.1101/255760" target="_blank">BioRxiv</a>.
Link to code on <a href="https://github.com/abannachbrown/The-use-of-text-mining-and-machine-learning-algorithms-in-systematic-reviews" target="_blank">GitHub</a>.



Visualisation of the topic-specific annotations of the Animal Models of depression dataset. Analysed using R. 

Link to app hosted by <a href="https://camarades.shinyapps.io/Preclinical-models-of-depression/" target="_blank">CAMARADES Shinyapp</a>. 
Link to code on <a href="https://github.com/abannachbrown/Regex-dictionary-app" target="_blank"> GitHub</a>. 



## 2017
Regular Expression Dictionaries: Topic-specific Dictionaries of Animal Models of Depression and Antidepressant Drugs for use in the Annotation of full-text documents in the depression dataset.

Link to code on <a href="github.com/abannachbrown/Depression-Project-CM" target="_blank">  GitHub</a>. Find other regular expression dictionaries for animal studies <a href="https://github.com/camaradesuk/RegexDictionaries" target="_blank">here.</a>